### ISSUE TITLE
Idea for upcoming challenges (Quantum Machine Learning)

### ISSUE THREAD

**Issue by Shiro-Raven** [qosf/monthly-challenges#23]
We haven't gotten our hands dirty with variational circuits so far. So I have the following idea for a challenge, for using variational circuits in a QML context:

1. Implement a regressional QML model for the IRIS dataset. This step shouldn't be too hard using Xanadu's libraries. 
2. Experiment with a [Quantum Autoencoder](https://arxiv.org/abs/1612.02806) and try to get the best compression of the quantum states of the input layer using a minimal number of qubits.

**Comment by amirebrahimi** [comment]
Thank you for your suggestion @Shiro-Raven - given either 1 or 2 (whichever one you find most interesting) would you be able to structure the problem similar to our previous problems where it has increasing levels of difficulty allowing for engagement commensurate to someone's skill level? You can also include a bonus/optional part of the challenge, too.

**Comment by Shiro-Raven** [comment]
I can somehow do it, but I would need someone with more QML experience/knowledge to verify that the difficulty of each step is uniformly distributed, once I prepare a draft.

Also, the 1 and 2 above were meant as parts of the whole challenge, where Part 1 can be implemented by following this [tutorial](https://pennylane.ai/qml/demos/tutorial_variational_classifier.html). And then, Part 2 would be the experimental part of the challenge where participants would try to compress the quantum information as much as they can. The fewer qubits the better. 

How does this sound?

**Comment by amirebrahimi** [comment]
Ah, I see. Sounds good. We were also looking for someone internally within our group with more domain experience to be able to validate the challenge.
