### ISSUE TITLE
QOSF Monthly  Challenge 

### ISSUE THREAD

**Issue by Dark-lord77** [qosf/monthly-challenges#3]

**Comment by aditya-giri** [comment]
Hi @Dark-lord77, did you mean to create this issue? What is it for?

**Comment by Dark-lord77** [comment]
Sorry sir I didn't get that
Did I have done something wrong?

**Comment by aditya-giri** [comment]
You opened this issue a couple of hours ago - do you wish to report or suggest something? If not, I will close this issue.

**Comment by Dark-lord77** [comment]
No sir
You can close it
